language: python

python:
  - "2.7"
  - "3.6"

install:
  - pip install pytest-cov
  - pip install pylint

script:
  - py.test --cov=. --cov-report xml --junitxml=report.xml
  - pylint splint

branches:
  only:
    - master
    - stable